
package Model;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author JOCTAN ESQUIVEL
 */
public class InterfazCocina extends javax.swing.JFrame {

    /**
     * Creates new form InterfazCocina
     */
    public InterfazCocina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrdenes = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txfNumeroOrden = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaNotificaciones = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cocina");
        setResizable(false);

        panel.setBackground(new java.awt.Color(16, 230, 255));
        panel.setForeground(new java.awt.Color(16, 230, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cocina");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Num Orden");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 190, 40));

        tblOrdenes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N. Orden", "Nombre", "Precio", "Completada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrdenes.setIntercellSpacing(new java.awt.Dimension(4, 4));
        tblOrdenes.setRowHeight(30);
        jScrollPane1.setViewportView(tblOrdenes);
        if (tblOrdenes.getColumnModel().getColumnCount() > 0) {
            tblOrdenes.getColumnModel().getColumn(0).setMinWidth(60);
            tblOrdenes.getColumnModel().getColumn(0).setPreferredWidth(60);
            tblOrdenes.getColumnModel().getColumn(0).setMaxWidth(75);
            tblOrdenes.getColumnModel().getColumn(1).setMinWidth(200);
            tblOrdenes.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblOrdenes.getColumnModel().getColumn(1).setMaxWidth(350);
            tblOrdenes.getColumnModel().getColumn(2).setMinWidth(75);
            tblOrdenes.getColumnModel().getColumn(2).setPreferredWidth(75);
            tblOrdenes.getColumnModel().getColumn(2).setMaxWidth(130);
            tblOrdenes.getColumnModel().getColumn(3).setMinWidth(65);
            tblOrdenes.getColumnModel().getColumn(3).setPreferredWidth(65);
            tblOrdenes.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 620, 450));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ordenes pendientes");
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 620, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Marcar completada");
        panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 380, 40));
        panel.add(txfNumeroOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 100, 40));

        btnAceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        panel.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 100, 40));

        txaNotificaciones.setBackground(new java.awt.Color(153, 255, 255));
        txaNotificaciones.setColumns(20);
        txaNotificaciones.setRows(5);
        jScrollPane2.setViewportView(txaNotificaciones);

        panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 380, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCocina().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tblOrdenes;
    private javax.swing.JTextArea txaNotificaciones;
    private javax.swing.JTextField txfNumeroOrden;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public void setBtnAceptar(JButton btnAceptar) {
        this.btnAceptar = btnAceptar;
    }

    public JTextArea getjTextArea1() {
        return txaNotificaciones;
    }

    public void setjTextArea1(JTextArea jTextArea1) {
        this.txaNotificaciones = jTextArea1;
    }

    public JTable getTblOrdenes() {
        return tblOrdenes;
    }

    public void setTblOrdenes(JTable tblOrdenes) {
        this.tblOrdenes = tblOrdenes;
    }

    public JTextField getTxfNumeroOrden() {
        return txfNumeroOrden;
    }

    public void setTxfNumeroOrden(JTextField txfNumeroOrden) {
        this.txfNumeroOrden = txfNumeroOrden;
    }

    
    
}
